services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: capstone_prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  backend:
    image: chaithanya013/backend:dev
    env_file:
      - .env.prod
    ports:
      - "5002:5000"
    depends_on:
      - db

  frontend:
    image: chaithanya013/frontend:dev
    ports:
      - "9092:80"
    depends_on:
      - backend

volumes:
  pgdata_prod: