services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: capstone_prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass

  backend:
    image: chaithanya013/backend:dev
    environment:
      DB_HOST: db
      DB_NAME: capstone_prod
      DB_USER: prod_user
      DB_PASSWORD: prod_pass
      APP_ENV: prod
    ports:
      - "5002:5000"
    depends_on:
      - db

  frontend:
    image: chaithanya013/frontend:dev
    ports:
      - "9092:80"
    depends_on:
      - backend
