services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: capstone_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  backend:
    image: chaithanya013/backend:dev
    env_file:
      - .env.dev
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: chaithanya013/frontend:dev
    ports:
      - "9090:80"
    depends_on:
      - backend

volumes:
  pgdata_dev:
