services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: capstone_staging
      POSTGRES_USER: stage_user
      POSTGRES_PASSWORD: stage_pass

  backend:
    image: chaithanya013/backend:dev
    environment:
      DB_HOST: db
      DB_NAME: capstone_staging
      DB_USER: stage_user
      DB_PASSWORD: stage_pass
      APP_ENV: staging
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    image: chaithanya013/frontend:dev
    ports:
      - "9091:80"
    depends_on:
      - backend
