services:
  services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: capstone_staging
      POSTGRES_USER: stage_user
      POSTGRES_PASSWORD: stage_pass
    volumes:
      - pgdata_staging:/var/lib/postgresql/data


  backend:
    image: chaithanya013/backend:dev
    env_file:
      - .env.staging
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    image: chaithanya013/frontend:dev
    ports:
      - "9091:80"
    depends_on:
      - backend
volumes:
  pgdata_staging:
