services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: capstone_staging
      POSTGRES_USER: staging_user
      POSTGRES_PASSWORD: staging_pass
    volumes:
      - pgdata_staging:/var/lib/postgresql/data

  backend:
    container_name: capstone-staging-backend
    image: chaithanya013/backend:staging
    env_file:
      - .env.staging
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    image: chaithanya013/frontend:staging
    ports:
      - "9091:80"
    depends_on:
      - backend

volumes:
  pgdata_staging:
